// <auto-generated />
namespace BookStore.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _CreateCountry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_CreateCountry));
        
        string IMigrationMetadata.Id
        {
            get { return "202601100651248__CreateCountry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
